artifact_location: file:C:/Users/sodar/Projects/WaveForm/runs/mlflow/410347355195609100
creation_time: 1772201412414
experiment_id: '410347355195609100'
last_update_time: 1772201412414
lifecycle_stage: active
name: /Shared/Ultralytics
workspace: default
