artifact_location: file:C:/Users/sodar/Projects/WaveForm/runs/mlflow/0
creation_time: 1772201412403
experiment_id: '0'
last_update_time: 1772201412403
lifecycle_stage: active
name: Default
workspace: default
